import { SoundLayer, DEFAULT_FX, DEFAULT_SYNTH } from '../types';

export interface SoundPreset {
  id: string;
  name: string;
  icon: string;
  description: string;
  apply: (layer: SoundLayer) => SoundLayer;
}

export const PRODUCER_SOUND_PRESETS: SoundPreset[] = [
  {
    id: 'sub-808-kick',
    name: '808 Sub Kick',
    icon: '🔊',
    description: 'Deep resonant sine sub with fast pitch drop punch',
    apply: (layer) => ({
      ...layer,
      name: `${layer.name || 'Layer'} (808 Sub)`,
      envelope: { attack: 0.001, decay: 0.55, sustain: 0.0, release: 0.25 },
      synth: {
        ...DEFAULT_SYNTH,
        oscType: 'sine',
        pitchEnvAmount: 36,
        pitchEnvDecay: 0.04,
        subLevel: 0.9,
      },
      fx: {
        ...DEFAULT_FX,
        filterEnabled: true,
        filterType: 'lowpass',
        filterFreq: 180,
        filterRes: 2.5,
        transientEnabled: true,
        transientAttack: 40,
        transientSustain: -20,
        filterDrive: 0.25,
      },
      macroPunch: 0.7,
      macroDepth: 0.9,
    }),
  },
  {
    id: 'crisp-trap-snare',
    name: 'Crisp Snare',
    icon: '⚡',
    description: 'Tight snap snare with noise body and mid bandpass boost',
    apply: (layer) => ({
      ...layer,
      name: `${layer.name || 'Layer'} (Snare)`,
      envelope: { attack: 0.001, decay: 0.18, sustain: 0.0, release: 0.1 },
      synth: {
        ...DEFAULT_SYNTH,
        oscType: 'sawtooth',
        pitchEnvAmount: 18,
        pitchEnvDecay: 0.02,
        cycleStretch: 0.3,
        fractalHarmonics: 0.4,
      },
      fx: {
        ...DEFAULT_FX,
        filterEnabled: true,
        filterType: 'bandpass',
        filterFreq: 2200,
        filterRes: 1.8,
        transientEnabled: true,
        transientAttack: 60,
        transientSustain: -40,
        tilTexture: 'grit',
        tilAmount: 0.45,
      },
      macroPunch: 0.8,
      macroGrit: 0.4,
    }),
  },
  {
    id: 'metallic-hihat',
    name: 'Metallic Hat',
    icon: '💫',
    description: 'Ultra-bright metallic hi-hat with highpass sizzle',
    apply: (layer) => ({
      ...layer,
      name: `${layer.name || 'Layer'} (HiHat)`,
      envelope: { attack: 0.001, decay: 0.06, sustain: 0.0, release: 0.04 },
      synth: {
        ...DEFAULT_SYNTH,
        oscType: 'square',
        osc2Type: 'sawtooth',
        osc2Mix: 0.5,
        osc2Detune: 7,
      },
      fx: {
        ...DEFAULT_FX,
        filterEnabled: true,
        filterType: 'highpass',
        filterFreq: 7500,
        filterRes: 3.0,
        transientEnabled: true,
        transientAttack: 50,
      },
      macroPunch: 0.6,
    }),
  },
  {
    id: 'sub-drop-sweep',
    name: 'Sub Drop Sweep',
    icon: '🌌',
    description: 'Cinematic low-end sub sweep with tube warmth',
    apply: (layer) => ({
      ...layer,
      name: `${layer.name || 'Layer'} (Sub Drop)`,
      envelope: { attack: 0.01, decay: 1.2, sustain: 0.1, release: 0.8 },
      synth: {
        ...DEFAULT_SYNTH,
        oscType: 'sine',
        pitchEnvAmount: 48,
        pitchEnvDecay: 0.35,
        subLevel: 1.0,
      },
      fx: {
        ...DEFAULT_FX,
        filterEnabled: true,
        filterType: 'lowpass',
        filterFreq: 220,
        filterRes: 1.5,
        filterDrive: 0.4,
      },
      macroDepth: 1.0,
      macroGrit: 0.3,
    }),
  },
  {
    id: 'glitch-pluck',
    name: 'Glitch Pluck',
    icon: '🌀',
    description: 'Fast-decay synth pluck with rhythmic LFO modulation',
    apply: (layer) => ({
      ...layer,
      name: `${layer.name || 'Layer'} (Pluck)`,
      envelope: { attack: 0.002, decay: 0.2, sustain: 0.0, release: 0.15 },
      synth: {
        ...DEFAULT_SYNTH,
        oscType: 'square',
        unisonVoices: 3,
        unisonDetune: 12,
        phaseChaos: 0.2,
      },
      fx: {
        ...DEFAULT_FX,
        filterEnabled: true,
        filterType: 'lowpass',
        filterFreq: 3200,
        filterRes: 4.0,
        lfoEnabled: true,
        lfoRate: 8,
        lfoDepth: 0.35,
        lfoTarget: 'filterFreq',
        distortion: 0.15,
      },
      macroPunch: 0.5,
      macroSpace: 0.4,
    }),
  },
  {
    id: 'ambient-warm-pad',
    name: 'Ambient Warm Pad',
    icon: '🌊',
    description: 'Lush 5-voice unison pad with smooth filter sweep',
    apply: (layer) => ({
      ...layer,
      name: `${layer.name || 'Layer'} (Ambient Pad)`,
      envelope: { attack: 0.4, decay: 1.5, sustain: 0.7, release: 1.2 },
      synth: {
        ...DEFAULT_SYNTH,
        oscType: 'sawtooth',
        osc2Type: 'sine',
        osc2Mix: 0.4,
        osc2Detune: 12,
        unisonVoices: 5,
        unisonDetune: 22,
      },
      fx: {
        ...DEFAULT_FX,
        filterEnabled: true,
        filterType: 'lowpass',
        filterFreq: 1800,
        filterRes: 1.2,
        lfoEnabled: true,
        lfoRate: 0.8,
        lfoDepth: 0.4,
        lfoTarget: 'pan',
        delayEnabled: true,
        delayTime: 0.3,
        delayFeedback: 0.45,
        reverbEnabled: true,
        reverbMix: 0.5,
      },
      macroSpace: 0.8,
    }),
  },
];
